### ISSUE TITLE
Nekonight storm colors a bit dark

### ISSUE THREAD

**Issue by toiletbowlkuku** [BrunoCiccarino/nekonight-vscode#1]
Are numbers supposed to be darker than comments? 

![Screenshot 2024-12-31 180522](https://github.com/user-attachments/assets/ef4635b9-7df1-4c47-95ed-2a50afa82170)

**Comment by BrunoCiccarino** [comment]
> Are numbers supposed to be darker than comments? 
> 
> ![Screenshot 2024-12-31 180522](https://github.com/user-attachments/assets/ef4635b9-7df1-4c47-95ed-2a50afa82170)
> 

Hi, happy new year, I think I wrote the color of the numbers, I'll fix it, it was supposed to be much clearer...

**Comment by BrunoCiccarino** [comment]
ready, I fixed it 
![issue1](https://github.com/user-attachments/assets/77a63a8c-ae13-4901-97a2-4d3a5b049e22)

**Comment by toiletbowlkuku** [comment]
Thanks for your work on this theme, Bruno. Really enjoying it so far.

Happy new year!

**Comment by BrunoCiccarino** [comment]
> Thanks for your work on this theme, Bruno. Really enjoying it so far.
> 
> Happy new year!

Thank you for your feedback, and happy new year to you too. :-)
